### ISSUE TITLE
Scalar "issue"

### ISSUE THREAD

**Issue by toastal** [purescript-graphql-client/purescript-graphql-client#20]
```
            {
              "name": "id",
              "description": null,
              "args": [

              ],
              "type": {
                "kind": "NON_NULL",
                "name": null,
                "ofType": {
                  "kind": "SCALAR",
                  "name": "CustomID",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": null
            },
```

The JSON doesn't tell you whether this is going to be a `String` or `Int` but it seems GraphQL allows either. Considering you probably won't/shouldn't be doing math the ID, users should probably be making sure they're sending strings. Since this is possible, perhaps it should be noted in the `README` somehow?

**Comment by srghma** [comment]
CustomID?

you can define custom scalars module

just like https://github.com/purescript-graphql-client/purescript-graphql-client/blob/master/examples/SwapiCustomScalars.purs

https://github.com/purescript-graphql-client/purescript-graphql-client/blob/0229e3e71176c456c716f7631261aab7b0ebb576/regenerate-examples.sh#L10

it will make generator to NOT generate default scalars module where all things are strings 

https://github.com/purescript-graphql-client/purescript-graphql-client/blob/master/examples/github/Scalars.purs

N.B. by graphQL spec the `ID` should be a string internally

____

yes, we should add a readme about custom scalars

**Comment by srghma** [comment]
Ok, this is resolved: all scalars are generated as strings right now, if one wants to change internal representation - he should use custom scalars

But by spec Id is string
