### ISSUE TITLE
Enum have Enum instance

### ISSUE THREAD

**Issue by toastal** [purescript-graphql-client/purescript-graphql-client#21]
https://pursuit.purescript.org/packages/purescript-enums/4.0.1/docs/Data.Enum#t:Enum

Seems to make sense.

This by proxy includes `Bounded` and `BoundedEnum`

**Comment by srghma** [comment]
I don't know, e.g. enabled/not_enabled enum

But if you want - you can add

**Comment by srghma** [comment]
OK, will close this

Enum doesn't make sense for some types

Its better to make custom scalar module:
- run generate, it will make default scalar module
- move that file somewhere, change module name, add custom classes
- run generate again with custom scalars option to regenerate imports

**Comment by toastal** [comment]
I disagree with this (I think). I believe in my cases and others, you would want to use an Enum in an `<select>` as `<option value>`s. It's with `BoundedEnum` you can get the list from top to bottom without needing to manually do this or keep it updated along with an easy `value`. Is this incorrect?

**Comment by srghma** [comment]
Yes, but generator may generate it in wrong order / derive, its better if BoundedEnum is defined by hand

BoundedEnum also doesn't make sense for some types
