### ISSUE TITLE
Testing the library out in a project

### ISSUE THREAD

**Issue by andrewMacmurray** [purescript-graphql-client/purescript-graphql-client#22]
Firstly thanks for open sourcing this - this is awesome work!

I'm pretty new to Purescript so I apologise if some of these things seem obvious, but was wondering what would be the steps for trying this out in a project (I'm guessing it's not in the default purescript packageset)?

**Comment by toastal** [comment]
You'll need to make some changes to your `package.dhall`. Firstly, you'll need to add

```dhall
      , graphql-client =
        { dependencies =
          [ "affjax"
          , "effect"
          , "generics-rep"
          , "node-fs-aff"
          , "prelude"
          , "proxy"
          , "psci-support"
          , "record"
          , "argonaut-core"
          , "argonaut-codecs"
          , "argonaut-generic"
          , "typelevel-prelude"
          , "debug"
          , "spec"
          , "variant"
          , "protolude"
          , "web-socket"
          , "unordered-collection"
          ]
        , repo =
            "https://github.com/purescript-graphql-client/purescript-graphql-client.git"
       -- whatever the latest git commit hash is
        , version = "ad19bb37083ba10fd6ab3b0fdd6770a343bb42a5"
        }
  ...
```

but you'll also need to get the dependencies that match this project including overrides to more recent versions of packages like `affjax`, `either`, `stings` and `strings-extra` as well as packages not in the default set like `protolude` and `unordered-collections`. I'd say reference this project's [`package.dhall`](https://github.com/purescript-graphql-client/purescript-graphql-client/blob/master/packages.dhall), but @srghma has hidden the dependencies behind a gist file and it's really difficult to tell what's needed if I'm being honest.

You can then use some JS package manager to install the precompiled  Node generator script from the latest commit hash as you can see in the [`README.md`](https://github.com/purescript-graphql-client/purescript-graphql-client/blob/master/README.md). From there you can see the `purescript-graphql-client-generator --help` for possible args. This generator will generate a number of typed `*.purs` files based on your GraphQL schema (as you can see [examples](https://github.com/purescript-graphql-client/purescript-graphql-client/tree/master/examples) that were already generated).

If you're looking for sample of consuming the generated files, @srghma has built a number of clear, solid [test cases](https://github.com/purescript-graphql-client/purescript-graphql-client/tree/master/examples-test/MyExamplesTests) that should give you a starting point for various queries and mutations.

This should be fairly similar the the [Elm GraphQL project](https://github.com/dillonkearns/elm-graphql/tree/master) noted as the main inspiration with a Node script that will auto-generate `*.elm` source files for you.

**Comment by srghma** [comment]
> I'd say reference this project's package.dhall, but @srghma has hidden the dependencies behind a gist file and it's really difficult to tell what's needed if I'm being honest

I will fix this soon

**Comment by andrewMacmurray** [comment]
That's awesome, thanks for this! Will give it a try this evening

**Comment by srghma** [comment]
now deps are explicit

https://github.com/purescript-graphql-client/purescript-graphql-client/blob/master/packages.dhall

**Comment by andrewMacmurray** [comment]
Got it installing now, cheers for all the input - I was trying to use it with a Hasura graphql server but there are cycles in the definition of some of the types so can't use it just yet (I see in the README you've got a TODO about potentially using  `Newtype`s). For any noobs wanting to try it out this is the full `packages.dhall` file I have:

```
let upstream =
      https://github.com/purescript/package-sets/releases/download/psc-0.13.8-20201021/packages.dhall sha256:55ebdbda1bd6ede4d5307fbc1ef19988c80271b4225d833c8d6fb9b6fb1aa6d8

let other =
  { ps-cst =
    { dependencies =
      [ "console"
      , "effect"
      , "generics-rep"
      , "psci-support"
      , "record"
      , "strings"
      , "spec"
      , "node-path"
      , "node-fs-aff"
      , "ansi"
      , "dodo-printer"
      ]
    , repo = "https://github.com/purescript-codegen/purescript-ps-cst.git"
    , version = "master"
    }
  , dodo-printer =
    { dependencies =
      [ "aff"
      , "ansi"
      , "avar"
      , "console"
      , "effect"
      , "foldable-traversable"
      , "lists"
      , "maybe"
      , "minibench"
      , "node-child-process"
      , "node-fs-aff"
      , "node-process"
      , "psci-support"
      , "strings"
      ]
    , repo = "https://github.com/natefaubion/purescript-dodo-printer.git"
    , version = "master"
    }
  , unordered-collection =
    { dependencies =
      [ "enums"
      , "functions"
      , "integers"
      , "lists"
      , "prelude"
      , "record"
      , "tuples"
      , "typelevel-prelude"
      ]
    , repo =
        "https://github.com/fehrenbach/purescript-unordered-collections.git"
    , version = "master"
    }
  , homogeneous-records =
    { dependencies =
      [ "record", "prelude", "typelevel-prelude", "unfoldable", "control" ]
    , repo = "https://github.com/srghma/purescript-homogeneous-records.git"
    , version = "master"
    }
  , mkdirp-aff =
    { dependencies =
      [ "prelude"
      , "effect"
      , "node-fs-aff"
      , "node-fs"
      , "node-path"
      , "either"
      , "exceptions"
      , "aff"
      ]
    , repo = "https://github.com/leighman/purescript-mkdirp-aff.git"
    , version = "master"
    }
  , url-regex-safe =
    { dependencies =
      [ "console"
      , "effect"
      , "psci-support"
      , "strings"
      ]
    , repo = "https://github.com/srghma/purescript-url-regex-safe.git"
    , version = "master"
    }
  , graphql-client =
    { dependencies =
        [ "affjax"
        , "effect"
        , "generics-rep"
        , "node-fs-aff"
        , "prelude"
        , "proxy"
        , "psci-support"
        , "record"
        , "argonaut-core"
        , "argonaut-codecs"
        , "argonaut-generic"
        , "typelevel-prelude"
        , "debug"
        , "spec"
        , "variant"
        , "unordered-collections"
        , "web-socket"
        ]
    , repo = "https://github.com/purescript-graphql-client/purescript-graphql-client.git"
    , version = "24a8ecdd138d431e11ed41e59bafbaf7c1df33db"
    }
  }

in (    upstream
    //  other
   )
  with affjax.version = "v11.0.0"
```

And then in `spago.dhall` add `graphql-client` to your dependency list

**Comment by srghma** [comment]
you have cycles in types, I understand this, yes, I had an idea to implement Newtypes, that should be easy, I just didnt encounter this problem in the wild

https://github.com/purescript-graphql-client/purescript-graphql-client/issues/24
