### ISSUE TITLE
circular deps in types -> generate code with newtypes

### ISSUE THREAD

**Issue by srghma** [purescript-graphql-client/purescript-graphql-client#24]
make this work https://github.com/purescript-graphql-client/purescript-graphql-client/blob/24a8ecdd138d431e11ed41e59bafbaf7c1df33db/regenerate-examples.sh#L18-L21

**Comment by srghma** [comment]
@andrewMacmurray

I have added newtypes in https://github.com/purescript-graphql-client/purescript-graphql-client/commit/6143c4a3aa5140c28d753520b3fc3ac1ce34aab1

but only for InputObjects, and IIUC this is the only object type that should be amended

could you confirm that this works for your app

**Comment by andrewMacmurray** [comment]
Fantastic, that was very quick! And can confirm it works too 🎉 Looking forward to trying this out on a personal project

**Comment by srghma** [comment]
tnx, closing then)
