### ISSUE TITLE
URL reader is wrong

### ISSUE THREAD

**Issue by toastal** [purescript-graphql-client/purescript-graphql-client#5]
`option --input-url: Can't parse as Url: "http://localhost:3000/graphql"`

This is a valid URL

**Comment by srghma** [comment]
probably comes from protolude url regex

working on migrating ps-cst to dodo-printer to resolve stack size crash

**Comment by srghma** [comment]
I can add you as a maintainer to this lib

**Comment by toastal** [comment]
np, sure

**Comment by srghma** [comment]
sent

**Comment by toastal** [comment]
It seemed to fail because there was no `.`... I had an alias with a `*.localhost` and it parsed fine
